services:
  web:
    image: nicholaskarimi/django-tenants:latest  # Pull the pre-built image from Docker Hub
    command: gunicorn --workers 3 --bind 0.0.0.0:9000 django_multitenant.wsgi:application
    volumes:
      - ./staticfiles:/tenants/staticfiles
      - ./media:/tenants/media
    expose:
      - 9000
    environment:
      - ENV=production
      - DEBUG=False
      - ALLOWED_HOSTS=tenants.com,102.220.22.107
    env_file: .env.prod


  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/tenants/staticfiles
      - ./media:/tenants/media
    container_name: tenants_nginx



volumes:
  static_volume:
  media_volune: