services:
  web:
    build: . # rebuild the image locally during development
    volumes:
      - .:/tenants  # Mount local files for real-time changes
    command: python manage.py runserver 0.0.0.0:9000

    environment:
      - ENV=development
      - DEBUG=True