services:
  web:
    image: nicholaskarimi/django-tenants:latest  # Pull the pre-built image from Docker Hub
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 tenants.wsgi:application
    volumes:
      - ./staticfiles:/tenants/staticfiles
      - ./media:/tenants/media
    expose:
      - 8000
    environment:
      - ENV=production
      - DEBUG=False
      - ALLOWED_HOSTS=tenants.com,102.210.149.111
    env_file: .env.prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://102.210.149.111/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./staticfiles:/tenants/staticfiles
      - ./media:/tenants/media
    container_name: tenants_nginx

      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/conf.d:/etc/nginx/conf.d
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://expenwise.com/health/"]

volumes:
  static_volume:
  media_volune: